config/routes.rb
Rails.application.routes.draw do

  resources :difficulties
  resources :types
  resources :tutorials

  root 'welcome#index'

end

app/models/difficulty.rb
class Difficulty < ActiveRecord::Base
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  validates_uniqueness_of :link
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  
  def index
  end
end

app/controllers/difficulties_controller.rb
class DifficultiesController < ApplicationController
  before_action :set_difficulty, only: [:show, :edit, :update, :destroy]

  # GET /difficulties
  # GET /difficulties.json
  def index
    @difficulties = Difficulty.all
  end

  # GET /difficulties/1
  # GET /difficulties/1.json
  def show
  end

  # GET /difficulties/new
  def new
    @difficulty = Difficulty.new
  end

  # GET /difficulties/1/edit
  def edit
  end

  # POST /difficulties
  # POST /difficulties.json
  def create
    @difficulty = Difficulty.new(difficulty_params)

    respond_to do |format|
      if @difficulty.save
        format.html { redirect_to @difficulty, notice: 'Difficulty was successfully created.' }
        format.json { render :show, status: :created, location: @difficulty }
      else
        format.html { render :new }
        format.json { render json: @difficulty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /difficulties/1
  # PATCH/PUT /difficulties/1.json
  def update
    respond_to do |format|
      if @difficulty.update(difficulty_params)
        format.html { redirect_to @difficulty, notice: 'Difficulty was successfully updated.' }
        format.json { render :show, status: :ok, location: @difficulty }
      else
        format.html { render :edit }
        format.json { render json: @difficulty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /difficulties/1
  # DELETE /difficulties/1.json
  def destroy
    @difficulty.destroy
    respond_to do |format|
      format.html { redirect_to difficulties_url, notice: 'Difficulty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_difficulty
      @difficulty = Difficulty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def difficulty_params
      params.require(:difficulty).permit(:name)
    end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
 #render json 

  def index
    @tutorials = Tutorial.all
    render json: @tutorials
  end

  def show 
    @tutorial = Tutorial.find params[:id]
    render json: @tutorial
  end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
    render json: @types
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type= Type.find params[:id]
    render json: @type
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/difficulties_helper.rb
module DifficultiesHelper
end

app/helpers/type_helper.rb
module TypeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/difficulties/_form.html.erb
<%= form_for(@difficulty) do |f| %>
  <% if @difficulty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@difficulty.errors.count, "error") %> prohibited this difficulty from being saved:</h2>

      <ul>
      <% @difficulty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/difficulties/edit.html.erb
<h1>Editing Difficulty</h1>

<%= render 'form' %>

<%= link_to 'Show', @difficulty %> |
<%= link_to 'Back', difficulties_path %>

app/views/difficulties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Difficulties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @difficulties.each do |difficulty| %>
      <tr>
        <td><%= difficulty.name %></td>
        <td><%= link_to 'Show', difficulty %></td>
        <td><%= link_to 'Edit', edit_difficulty_path(difficulty) %></td>
        <td><%= link_to 'Destroy', difficulty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Difficulty', new_difficulty_path %>

app/views/difficulties/new.html.erb
<h1>New Difficulty</h1>

<%= render 'form' %>

<%= link_to 'Back', difficulties_path %>

app/views/difficulties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @difficulty.name %>
</p>

<%= link_to 'Edit', edit_difficulty_path(@difficulty) %> |
<%= link_to 'Back', difficulties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RocketLeagueTutorials" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">RocketLeagueTutorials</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/type/index.html.erb
<h1>Type#index</h1>
<p>Find me in app/views/type/index.html.erb</p>

app/views/type/show.html.erb
<h1>Type#show</h1>
<p>Find me in app/views/type/show.html.erb</p>

app/views/welcome/index.html.erb
<div id="app">
  <h1>Rocket League Tutorials</h1>
  <body>
    <form>
      Tutorial Type:
      <select id="type">
        <%=  options_from_collection_for_select(Type.all, :id, :name) %>
      </select>
      Difficulty:
      <select id="difficulty">
        <%= options_from_collection_for_select(Difficulty.all, :id, :name) %>
      </select>
    </form>
  </body>
  <ul class="type"></ul>
</div>